In [1]:
import os
import os.path as osp
import numpy as np
from easydict import EasyDict as edict

In [2]:
__C = edict()
__C.name = 'YQS'
__C.birthday = '1992-12-21'

In [3]:
__C

{'name': 'YQS', 'birthday': '1992-12-21'}

In [4]:
import tensorflow as tf 
from tensorflow import keras 

import os

# os.environ['CUDA_VISIBLE_DEVICES'] = '/gpu:5'

# 生成conv5的特征矩阵

In [5]:
conv_5 = tf.ones([10, 10, 2048], tf.float32)
conv_5_L = tf.expand_dims(conv_5, axis=0)
conv_5_L

<tf.Tensor: id=4, shape=(1, 10, 10, 2048), dtype=float32, numpy=
array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        ...,

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1

In [6]:
rpn_conv = keras.layers.Conv2D(filters=512, kernel_size=(3, 3), padding='same', name='rpn_conv/3x3')(conv_5_L)
rpn_conv

<tf.Tensor: id=32, shape=(1, 10, 10, 512), dtype=float32, numpy=
array([[[[ 0.65056074, -1.3889656 ,  1.0651019 , ..., -0.57699156,
          -0.5297555 , -1.4415731 ],
         [ 1.0461218 , -0.9311396 ,  1.0687875 , ..., -0.34389985,
          -0.47418642, -1.8401897 ],
         [ 1.0461218 , -0.9311396 ,  1.0687875 , ..., -0.34389985,
          -0.47418642, -1.8401897 ],
         ...,
         [ 1.0461218 , -0.9311396 ,  1.0687875 , ..., -0.34389985,
          -0.47418642, -1.8401897 ],
         [ 1.0461218 , -0.9311396 ,  1.0687875 , ..., -0.34389985,
          -0.47418642, -1.8401897 ],
         [-0.32651716, -1.1047683 ,  0.5845647 , ...,  0.21179722,
          -0.21408254, -1.553521  ]],

        [[ 0.22951806, -2.2619615 ,  1.6200576 , ..., -1.0819285 ,
          -0.16319904, -1.2928634 ],
         [ 0.12498277, -2.055742  ,  0.8360008 , ..., -1.3512107 ,
           0.22867042, -2.4515345 ],
         [ 0.12498277, -2.055742  ,  0.8360008 , ..., -1.3512107 ,
           0.2286704

In [8]:
keras.layers.Conv2D?

In [7]:
rpn_cls_score = keras.layers.Conv2D(filters=9*2, kernel_size=(1, 1), name='rpn_cls_score')(rpn_conv)
rpn_cls_score

<tf.Tensor: id=59, shape=(1, 10, 10, 18), dtype=float32, numpy=
array([[[[-0.91090864,  0.30755782, -0.18779697, ...,  0.22777966,
          -0.746752  ,  1.031409  ],
         [-1.4513845 , -0.26173425,  0.4905176 , ..., -0.12344304,
          -1.7628934 ,  0.759557  ],
         [-1.4513845 , -0.26173425,  0.4905176 , ..., -0.12344304,
          -1.7628934 ,  0.759557  ],
         ...,
         [-1.4513845 , -0.26173425,  0.4905176 , ..., -0.12344304,
          -1.7628934 ,  0.759557  ],
         [-1.4513845 , -0.26173425,  0.4905176 , ..., -0.12344304,
          -1.7628934 ,  0.759557  ],
         [-0.790048  , -0.14550734,  1.0183473 , ..., -0.30590263,
          -1.850531  ,  1.4294938 ]],

        [[-0.62808627,  1.1513759 , -0.46017748, ...,  1.1156857 ,
          -0.9319042 ,  1.0159293 ],
         [-2.444634  ,  0.81489176, -0.01212206, ...,  0.532583  ,
          -0.50946444,  1.0840802 ],
         [-2.444634  ,  0.81489176, -0.01212206, ...,  0.532583  ,
          -0.50946444

In [8]:
rpn_cls_score_temp = keras.layers.Conv2D(filters=9, kernel_size=(1, 1), name='rpn_cls_score')(rpn_conv)
print(rpn_cls_score_temp)
rpn_cls_score_temp = keras.layers.Activation('sigmoid')(rpn_cls_score_temp)
print(rpn_cls_score_temp)

tf.Tensor(
[[[[-0.8142584  -0.6091598  -1.3498785  -0.25901723 -1.8931851
     0.09576991 -0.9429995  -0.4703152   0.5592228 ]
   [-0.61203504  0.59479195 -1.9954865  -0.4457505  -2.9992914
    -1.3846049  -1.8391833   0.6876793   1.5112371 ]
   [-0.61203504  0.59479195 -1.9954865  -0.4457505  -2.9992914
    -1.3846049  -1.8391833   0.6876793   1.5112371 ]
   [-0.61203504  0.59479195 -1.9954865  -0.4457505  -2.9992914
    -1.3846049  -1.8391833   0.6876793   1.5112371 ]
   [-0.61203504  0.59479195 -1.9954865  -0.4457505  -2.9992914
    -1.3846049  -1.8391833   0.6876793   1.5112371 ]
   [-0.61203504  0.59479195 -1.9954865  -0.4457505  -2.9992914
    -1.3846049  -1.8391833   0.6876793   1.5112371 ]
   [-0.61203504  0.59479195 -1.9954865  -0.4457505  -2.9992914
    -1.3846049  -1.8391833   0.6876793   1.5112371 ]
   [-0.61203504  0.59479195 -1.9954865  -0.4457505  -2.9992914
    -1.3846049  -1.8391833   0.6876793   1.5112371 ]
   [-0.61203504  0.59479195 -1.9954865  -0.4457505  -2.999291

In [39]:
keras.layers.Activation?

In [9]:
def _reshape_layer(bottom, num_dim):
    input_shape = tf.shape(bottom)
    # change the channel to the caffe format
    to_caffe = tf.transpose(bottom, [0, 3, 1, 2])
    # then force it to have channel 2
    reshaped = tf.reshape(to_caffe,
                        tf.concat(axis=0, values=[[1, num_dim, -1], [input_shape[2]]]))
    # then swap the channel back
    to_tf = tf.transpose(reshaped, [0, 2, 3, 1])
    return to_tf

def _softmax_layer(bottom, name):
    if name.startswith('rpn_cls_prob_reshape'):
        input_shape = tf.shape(bottom)
        bottom_reshaped = tf.reshape(bottom, [-1, input_shape[-1]])
        reshaped_score = tf.nn.softmax(bottom_reshaped, name=name)
        return tf.reshape(reshaped_score, input_shape)
    return tf.nn.softmax(bottom, name=name)

In [10]:
input_shape = tf.shape(rpn_cls_score)
input_shape

<tf.Tensor: id=88, shape=(4,), dtype=int32, numpy=array([ 1, 10, 10, 18])>

In [11]:
to_caffe = tf.transpose(rpn_cls_score, [0, 3, 1, 2])
to_caffe 

<tf.Tensor: id=90, shape=(1, 18, 10, 10), dtype=float32, numpy=
array([[[[-0.91090864, -1.4513845 , -1.4513845 , ..., -1.4513845 ,
          -1.4513845 , -0.790048  ],
         [-0.62808627, -2.444634  , -2.444634  , ..., -2.444634  ,
          -2.444634  , -2.4030945 ],
         [-0.62808627, -2.444634  , -2.444634  , ..., -2.444634  ,
          -2.444634  , -2.4030945 ],
         ...,
         [-0.62808627, -2.444634  , -2.444634  , ..., -2.444634  ,
          -2.444634  , -2.4030945 ],
         [-0.62808627, -2.444634  , -2.444634  , ..., -2.444634  ,
          -2.444634  , -2.4030945 ],
         [ 0.36831817, -1.055627  , -1.055627  , ..., -1.055627  ,
          -1.055627  , -1.8992658 ]],

        [[ 0.30755782, -0.26173425, -0.26173425, ..., -0.26173425,
          -0.26173425, -0.14550734],
         [ 1.1513759 ,  0.81489176,  0.81489176, ...,  0.81489176,
           0.81489176,  1.1569513 ],
         [ 1.1513759 ,  0.81489176,  0.81489176, ...,  0.81489176,
           0.81489176

In [12]:
print(tf.concat(axis=0, values=[[1, 2, -1], [input_shape[2]]]))
reshaped = tf.reshape(to_caffe,
                    tf.concat(axis=0, values=[[1, 2, -1], [input_shape[2]]]))
reshaped

tf.Tensor([ 1  2 -1 10], shape=(4,), dtype=int32)


<tf.Tensor: id=107, shape=(1, 2, 90, 10), dtype=float32, numpy=
array([[[[-0.91090864, -1.4513845 , -1.4513845 , ..., -1.4513845 ,
          -1.4513845 , -0.790048  ],
         [-0.62808627, -2.444634  , -2.444634  , ..., -2.444634  ,
          -2.444634  , -2.4030945 ],
         [-0.62808627, -2.444634  , -2.444634  , ..., -2.444634  ,
          -2.444634  , -2.4030945 ],
         ...,
         [-0.91389114, -1.0771663 , -1.0771663 , ..., -1.0771663 ,
          -1.0771663 ,  0.10056928],
         [-0.91389114, -1.0771663 , -1.0771663 , ..., -1.0771663 ,
          -1.0771663 ,  0.10056928],
         [-0.40961707, -0.66778207, -0.66778207, ..., -0.66778207,
          -0.66778207, -0.5345525 ]],

        [[-0.8843367 , -2.7236943 , -2.7236943 , ..., -2.7236943 ,
          -2.7236943 , -2.2527385 ],
         [-0.97892076, -2.772812  , -2.772812  , ..., -2.772812  ,
          -2.772812  , -2.3886454 ],
         [-0.97892076, -2.772812  , -2.772812  , ..., -2.772812  ,
          -2.772812  

In [13]:
rpn_cls_score_reshape = _reshape_layer(rpn_cls_score, 2)
rpn_cls_score_reshape

<tf.Tensor: id=121, shape=(1, 90, 10, 2), dtype=float32, numpy=
array([[[[-0.91090864, -0.8843367 ],
         [-1.4513845 , -2.7236943 ],
         [-1.4513845 , -2.7236943 ],
         ...,
         [-1.4513845 , -2.7236943 ],
         [-1.4513845 , -2.7236943 ],
         [-0.790048  , -2.2527385 ]],

        [[-0.62808627, -0.97892076],
         [-2.444634  , -2.772812  ],
         [-2.444634  , -2.772812  ],
         ...,
         [-2.444634  , -2.772812  ],
         [-2.444634  , -2.772812  ],
         [-2.4030945 , -2.3886454 ]],

        [[-0.62808627, -0.97892076],
         [-2.444634  , -2.772812  ],
         [-2.444634  , -2.772812  ],
         ...,
         [-2.444634  , -2.772812  ],
         [-2.444634  , -2.772812  ],
         [-2.4030945 , -2.3886454 ]],

        ...,

        [[-0.91389114,  1.0159293 ],
         [-1.0771663 ,  1.0840802 ],
         [-1.0771663 ,  1.0840802 ],
         ...,
         [-1.0771663 ,  1.0840802 ],
         [-1.0771663 ,  1.0840802 ],
         

In [14]:
rpn_cls_prob_reshape = _softmax_layer(rpn_cls_score_reshape, "rpn_cls_prob_reshape")
rpn_cls_prob_reshape

<tf.Tensor: id=131, shape=(1, 90, 10, 2), dtype=float32, numpy=
array([[[[0.4933574 , 0.5066426 ],
         [0.7811379 , 0.2188621 ],
         [0.7811379 , 0.2188621 ],
         ...,
         [0.7811379 , 0.2188621 ],
         [0.7811379 , 0.2188621 ],
         [0.8119438 , 0.18805617]],

        [[0.58681995, 0.41318008],
         [0.581316  , 0.41868404],
         [0.581316  , 0.41868404],
         ...,
         [0.581316  , 0.41868404],
         [0.581316  , 0.41868404],
         [0.49638778, 0.5036122 ]],

        [[0.58681995, 0.41318008],
         [0.581316  , 0.41868404],
         [0.581316  , 0.41868404],
         ...,
         [0.581316  , 0.41868404],
         [0.581316  , 0.41868404],
         [0.49638778, 0.5036122 ]],

        ...,

        [[0.12677045, 0.87322956],
         [0.10328494, 0.89671504],
         [0.10328494, 0.89671504],
         ...,
         [0.10328494, 0.89671504],
         [0.10328494, 0.89671504],
         [0.1055264 , 0.8944736 ]],

        [[0.126770

In [15]:
temp = tf.reshape(rpn_cls_score_reshape, [-1, 2])
temp 

<tf.Tensor: id=133, shape=(900, 2), dtype=float32, numpy=
array([[-0.91090864, -0.8843367 ],
       [-1.4513845 , -2.7236943 ],
       [-1.4513845 , -2.7236943 ],
       ...,
       [-0.66778207,  0.6488037 ],
       [-0.66778207,  0.6488037 ],
       [-0.5345525 ,  1.3106806 ]], dtype=float32)>

In [16]:
rpn_cls_pred = tf.argmax(tf.reshape(rpn_cls_score_reshape, [-1, 2]), axis=1, name="rpn_cls_pred")
rpn_cls_pred

<tf.Tensor: id=137, shape=(900,), dtype=int64, numpy=
array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [17]:
# 计算每个锚框是不是前景的概率
rpn_cls_prob = _reshape_layer(rpn_cls_prob_reshape, 18)
rpn_cls_prob

<tf.Tensor: id=151, shape=(1, 10, 10, 18), dtype=float32, numpy=
array([[[[0.4933574 , 0.4035085 , 0.22328016, ..., 0.88464415,
          0.27805662, 0.86692023],
         [0.7811379 , 0.2847961 , 0.30201834, ..., 0.8676792 ,
          0.0151673 , 0.72365284],
         [0.7811379 , 0.2847961 , 0.30201834, ..., 0.8676792 ,
          0.0151673 , 0.72365284],
         ...,
         [0.7811379 , 0.2847961 , 0.30201834, ..., 0.8676792 ,
          0.0151673 , 0.72365284],
         [0.7811379 , 0.2847961 , 0.30201834, ..., 0.8676792 ,
          0.0151673 , 0.72365284],
         [0.8119438 , 0.3876143 , 0.6553682 , ..., 0.8034552 ,
          0.0101162 , 0.63799596]],

        [[0.58681995, 0.7561563 , 0.1385337 , ..., 0.85782397,
          0.37621784, 0.87322956],
         [0.581316  , 0.6968098 , 0.08754007, ..., 0.84660023,
          0.20578441, 0.89671504],
         [0.581316  , 0.6968098 , 0.08754007, ..., 0.84660023,
          0.20578441, 0.89671504],
         ...,
         [0.581316  , 0

In [18]:
# 网络计算锚框左上角与右下角的值，两个点的四个坐标值
rpn_bbox_pred = keras.layers.Conv2D(filters=9*4, kernel_size=(1, 1), name='rpn_bbox_pred')(rpn_conv)
rpn_bbox_pred

<tf.Tensor: id=178, shape=(1, 10, 10, 36), dtype=float32, numpy=
array([[[[-8.3103436e-01,  8.8799763e-01, -7.2093213e-01, ...,
          -1.1532059e+00,  2.6058620e-01,  9.4721824e-02],
         [ 1.7066631e-01,  6.5971100e-01, -3.1119856e-01, ...,
           9.3484640e-02, -5.6444395e-01,  4.3101060e-01],
         [ 1.7066631e-01,  6.5971100e-01, -3.1119856e-01, ...,
           9.3484640e-02, -5.6444395e-01,  4.3101060e-01],
         ...,
         [ 1.7066631e-01,  6.5971100e-01, -3.1119856e-01, ...,
           9.3484640e-02, -5.6444395e-01,  4.3101060e-01],
         [ 1.7066631e-01,  6.5971100e-01, -3.1119856e-01, ...,
           9.3484640e-02, -5.6444395e-01,  4.3101060e-01],
         [ 1.0464566e+00,  3.6403379e-01,  1.8228787e-01, ...,
          -3.3086538e-04, -7.2539645e-01,  1.2174919e+00]],

        [[-8.0009890e-01, -3.7141079e-01,  1.1723414e-02, ...,
          -1.9748273e+00, -2.2101809e-01,  1.4501283e+00],
         [ 1.0829587e+00,  9.8477018e-01,  2.2569126e-01, ...,
  

In [19]:
from generate_anchors import generate_anchors

In [20]:
def generate_anchors_pre_tf(height, width, feat_stride=16, anchor_scales=(8, 16, 32), anchor_ratios=(0.5, 1, 2)):
    shift_x = tf.range(width) * feat_stride # width
    shift_y = tf.range(height) * feat_stride # height
    shift_x, shift_y = tf.meshgrid(shift_x, shift_y)
    sx = tf.reshape(shift_x, shape=(-1,))
    sy = tf.reshape(shift_y, shape=(-1,))
    shifts = tf.transpose(tf.stack([sx, sy, sx, sy]))
    K = tf.multiply(width, height)
    shifts = tf.transpose(tf.reshape(shifts, shape=[1, K, 4]), perm=(1, 0, 2))

    anchors = generate_anchors(ratios=np.array(anchor_ratios), scales=np.array(anchor_scales))
    A = anchors.shape[0]
    anchor_constant = tf.constant(anchors.reshape((1, A, 4)), dtype=tf.int32)

    length = K * A
    anchors_tf = tf.reshape(tf.add(anchor_constant, shifts), shape=(length, 4))

    return tf.cast(anchors_tf, dtype=tf.float32), length

In [21]:
# 设置基本变量
pre_nms_topN = 12000
post_nms_topN = 2000
nms_thresh = 0.7
im_info = [160, 160, 1.2]
feat_stride = 16 
conv_5_width, conv_5_height = 10, 10

In [24]:
anchors, length = generate_anchors_pre_tf(conv_5_width, conv_5_height, feat_stride=feat_stride)
anchors, length

(<tf.Tensor: id=343, shape=(900, 4), dtype=float32, numpy=
 array([[ -84.,  -40.,   99.,   55.],
        [-176.,  -88.,  191.,  103.],
        [-360., -184.,  375.,  199.],
        ...,
        [ 108.,   64.,  195.,  239.],
        [  64.,  -24.,  239.,  327.],
        [ -24., -200.,  327.,  503.]], dtype=float32)>,
 <tf.Tensor: id=338, shape=(), dtype=int32, numpy=900>)

In [26]:
# Get the scores and bounding boxes
num_anchors = 9
scores = rpn_cls_prob[:, :, :, num_anchors:]
rpn_cls_prob, scores

(<tf.Tensor: id=151, shape=(1, 10, 10, 18), dtype=float32, numpy=
 array([[[[0.4933574 , 0.4035085 , 0.22328016, ..., 0.88464415,
           0.27805662, 0.86692023],
          [0.7811379 , 0.2847961 , 0.30201834, ..., 0.8676792 ,
           0.0151673 , 0.72365284],
          [0.7811379 , 0.2847961 , 0.30201834, ..., 0.8676792 ,
           0.0151673 , 0.72365284],
          ...,
          [0.7811379 , 0.2847961 , 0.30201834, ..., 0.8676792 ,
           0.0151673 , 0.72365284],
          [0.7811379 , 0.2847961 , 0.30201834, ..., 0.8676792 ,
           0.0151673 , 0.72365284],
          [0.8119438 , 0.3876143 , 0.6553682 , ..., 0.8034552 ,
           0.0101162 , 0.63799596]],
 
         [[0.58681995, 0.7561563 , 0.1385337 , ..., 0.85782397,
           0.37621784, 0.87322956],
          [0.581316  , 0.6968098 , 0.08754007, ..., 0.84660023,
           0.20578441, 0.89671504],
          [0.581316  , 0.6968098 , 0.08754007, ..., 0.84660023,
           0.20578441, 0.89671504],
          ...,
 

In [27]:
scores = tf.reshape(scores, shape=(-1,))
scores

<tf.Tensor: id=353, shape=(900,), dtype=float32, numpy=
array([0.5066426 , 0.5964914 , 0.7767198 , 0.666015  , 0.5579602 ,
       0.03464269, 0.88464415, 0.27805662, 0.86692023, 0.2188621 ,
       0.7152039 , 0.69798166, 0.79432523, 0.41918203, 0.06388939,
       0.8676792 , 0.0151673 , 0.72365284, 0.2188621 , 0.7152039 ,
       0.69798166, 0.79432523, 0.41918203, 0.06388939, 0.8676792 ,
       0.0151673 , 0.72365284, 0.2188621 , 0.7152039 , 0.69798166,
       0.79432523, 0.41918203, 0.06388939, 0.8676792 , 0.0151673 ,
       0.72365284, 0.2188621 , 0.7152039 , 0.69798166, 0.79432523,
       0.41918203, 0.06388939, 0.8676792 , 0.0151673 , 0.72365284,
       0.2188621 , 0.7152039 , 0.69798166, 0.79432523, 0.41918203,
       0.06388939, 0.8676792 , 0.0151673 , 0.72365284, 0.2188621 ,
       0.7152039 , 0.69798166, 0.79432523, 0.41918203, 0.06388939,
       0.8676792 , 0.0151673 , 0.72365284, 0.2188621 , 0.7152039 ,
       0.69798166, 0.79432523, 0.41918203, 0.06388939, 0.8676792 ,
      

In [28]:
rpn_bbox_pred
rpn_bbox_pred = tf.reshape(rpn_bbox_pred, shape=(-1, 4))
rpn_bbox_pred

<tf.Tensor: id=355, shape=(900, 4), dtype=float32, numpy=
array([[-0.83103436,  0.8879976 , -0.7209321 , -1.6348817 ],
       [-0.33042908, -0.0967989 ,  0.4130898 ,  0.94864386],
       [ 0.9771678 ,  0.29312342, -1.5942672 ,  2.9608483 ],
       ...,
       [ 0.06816399, -1.80386   ,  1.1643107 , -1.1432757 ],
       [ 0.9387727 ,  0.60236454, -1.7344823 , -1.1435287 ],
       [ 0.2292346 , -2.5345771 ,  0.54480946,  1.5146002 ]],
      dtype=float32)>

In [29]:
def bbox_transform_inv_tf(boxes, deltas):
    boxes = tf.cast(boxes, deltas.dtype)
    widths = tf.subtract(boxes[:, 2], boxes[:, 0]) + 1.0
    heights = tf.subtract(boxes[:, 3], boxes[:, 1]) + 1.0
    ctr_x = tf.add(boxes[:, 0], widths * 0.5)
    ctr_y = tf.add(boxes[:, 1], heights * 0.5)

    dx = deltas[:, 0]
    dy = deltas[:, 1]
    dw = deltas[:, 2]
    dh = deltas[:, 3]

    pred_ctr_x = tf.add(tf.multiply(dx, widths), ctr_x)
    pred_ctr_y = tf.add(tf.multiply(dy, heights), ctr_y)
    pred_w = tf.multiply(tf.exp(dw), widths)
    pred_h = tf.multiply(tf.exp(dh), heights)

    pred_boxes0 = tf.subtract(pred_ctr_x, pred_w * 0.5)
    pred_boxes1 = tf.subtract(pred_ctr_y, pred_h * 0.5)
    pred_boxes2 = tf.add(pred_ctr_x, pred_w * 0.5)
    pred_boxes3 = tf.add(pred_ctr_y, pred_h * 0.5)

    return tf.stack([pred_boxes0, pred_boxes1, pred_boxes2, pred_boxes3], axis=1)


def clip_boxes_tf(boxes, im_info):
    b0 = tf.maximum(tf.minimum(boxes[:, 0], im_info[1] - 1), 0)
    b1 = tf.maximum(tf.minimum(boxes[:, 1], im_info[0] - 1), 0)
    b2 = tf.maximum(tf.minimum(boxes[:, 2], im_info[1] - 1), 0)
    b3 = tf.maximum(tf.minimum(boxes[:, 3], im_info[0] - 1), 0)
    return tf.stack([b0, b1, b2, b3], axis=1)

In [30]:
proposals = bbox_transform_inv_tf(anchors, rpn_bbox_pred)
proposals = clip_boxes_tf(proposals, im_info[:2])
proposals

<tf.Tensor: id=461, shape=(900, 4), dtype=float32, numpy=
array([[  0.      ,  83.888954,   0.      , 102.60659 ],
       [  0.      ,   0.      , 159.      , 159.      ],
       [159.      ,   0.      , 159.      , 159.      ],
       ...,
       [ 17.035019,   0.      , 159.      ,   0.      ],
       [159.      , 159.      , 159.      , 159.      ],
       [  0.      ,   0.      , 159.      ,   0.      ]], dtype=float32)>

In [32]:
boxes = tf.cast(anchors, rpn_bbox_pred.dtype)
widths = tf.subtract(boxes[:, 2], boxes[:, 0]) + 1.0
heights = tf.subtract(boxes[:, 3], boxes[:, 1]) + 1.0
ctr_x = tf.add(boxes[:, 0], widths * 0.5)
ctr_y = tf.add(boxes[:, 1], heights * 0.5)
widths, heights, ctr_x, ctr_y

(<tf.Tensor: id=508, shape=(900,), dtype=float32, numpy=
 array([184., 368., 736., 128., 256., 512.,  88., 176., 352., 184., 368.,
        736., 128., 256., 512.,  88., 176., 352., 184., 368., 736., 128.,
        256., 512.,  88., 176., 352., 184., 368., 736., 128., 256., 512.,
         88., 176., 352., 184., 368., 736., 128., 256., 512.,  88., 176.,
        352., 184., 368., 736., 128., 256., 512.,  88., 176., 352., 184.,
        368., 736., 128., 256., 512.,  88., 176., 352., 184., 368., 736.,
        128., 256., 512.,  88., 176., 352., 184., 368., 736., 128., 256.,
        512.,  88., 176., 352., 184., 368., 736., 128., 256., 512.,  88.,
        176., 352., 184., 368., 736., 128., 256., 512.,  88., 176., 352.,
        184., 368., 736., 128., 256., 512.,  88., 176., 352., 184., 368.,
        736., 128., 256., 512.,  88., 176., 352., 184., 368., 736., 128.,
        256., 512.,  88., 176., 352., 184., 368., 736., 128., 256., 512.,
         88., 176., 352., 184., 368., 736., 128., 256.,

In [33]:
dx = rpn_bbox_pred[:, 0]
dy = rpn_bbox_pred[:, 1]
dw = rpn_bbox_pred[:, 2]
dh = rpn_bbox_pred[:, 3]
dx, dy, dw, dh

(<tf.Tensor: id=537, shape=(900,), dtype=float32, numpy=
 array([-0.83103436, -0.33042908,  0.9771678 , -0.3390693 ,  0.186342  ,
        -0.9960917 ,  1.260816  ,  1.0984414 ,  0.38532847,  0.1706663 ,
        -1.2392529 ,  0.48829377, -0.73588145, -0.60311955, -1.8378345 ,
         1.0402975 ,  0.3662023 ,  0.74424183,  0.1706663 , -1.2392529 ,
         0.48829377, -0.73588145, -0.60311955, -1.8378345 ,  1.0402975 ,
         0.3662023 ,  0.74424183,  0.1706663 , -1.2392529 ,  0.48829377,
        -0.73588145, -0.60311955, -1.8378345 ,  1.0402975 ,  0.3662023 ,
         0.74424183,  0.1706663 , -1.2392529 ,  0.48829377, -0.73588145,
        -0.60311955, -1.8378345 ,  1.0402975 ,  0.3662023 ,  0.74424183,
         0.1706663 , -1.2392529 ,  0.48829377, -0.73588145, -0.60311955,
        -1.8378345 ,  1.0402975 ,  0.3662023 ,  0.74424183,  0.1706663 ,
        -1.2392529 ,  0.48829377, -0.73588145, -0.60311955, -1.8378345 ,
         1.0402975 ,  0.3662023 ,  0.74424183,  0.1706663 , -1.2392

In [35]:
pred_ctr_x = tf.add(tf.multiply(dx, widths), ctr_x)
pred_ctr_y = tf.add(tf.multiply(dy, heights), ctr_y)
pred_w = tf.multiply(tf.exp(dw), widths)
pred_h = tf.multiply(tf.exp(dh), heights)
pred_ctr_x, pred_ctr_y, pred_w, pred_h

(<tf.Tensor: id=552, shape=(900,), dtype=float32, numpy=
 array([-1.44910324e+02, -1.13597900e+02,  7.27195496e+02, -3.54008713e+01,
         5.57035522e+01, -5.01998962e+02,  1.18951805e+02,  2.01325684e+02,
         1.43635620e+02,  5.54026031e+01, -4.32045074e+02,  3.83384216e+02,
        -7.01928253e+01, -1.30398605e+02, -9.16971252e+02,  1.15546181e+02,
         8.84516068e+01,  2.85973114e+02,  7.14026031e+01, -4.16045074e+02,
         3.99384216e+02, -5.41928253e+01, -1.14398605e+02, -9.00971252e+02,
         1.31546173e+02,  1.04451607e+02,  3.01973114e+02,  8.74026031e+01,
        -4.00045074e+02,  4.15384216e+02, -3.81928253e+01, -9.83986053e+01,
        -8.84971252e+02,  1.47546173e+02,  1.20451607e+02,  3.17973114e+02,
         1.03402603e+02, -3.84045074e+02,  4.31384216e+02, -2.21928253e+01,
        -8.23986053e+01, -8.68971252e+02,  1.63546173e+02,  1.36451599e+02,
         3.33973114e+02,  1.19402603e+02, -3.68045074e+02,  4.47384216e+02,
        -6.19282532e+00, -6.639

In [37]:
pred_boxes0 = tf.subtract(pred_ctr_x, pred_w * 0.5)
pred_boxes1 = tf.subtract(pred_ctr_y, pred_h * 0.5)
pred_boxes2 = tf.add(pred_ctr_x, pred_w * 0.5)
pred_boxes3 = tf.add(pred_ctr_y, pred_h * 0.5)
pred_boxes0, pred_boxes1, pred_boxes2, pred_boxes3

(<tf.Tensor: id=562, shape=(900,), dtype=float32, numpy=
 array([-1.89649811e+02, -3.91710358e+02,  6.52470398e+02, -7.23493805e+01,
        -1.50793533e+01, -1.65552173e+03, -3.41536896e+02,  1.08631035e+02,
        -8.47579346e+01, -1.19936905e+01, -8.65727173e+02,  3.27986969e+02,
        -1.55200119e+02, -2.71919495e+02, -1.01344111e+04, -3.19154785e+02,
         6.12204437e+01,  1.85886078e+02,  4.00630951e+00, -8.49727173e+02,
         3.43986969e+02, -1.39200119e+02, -2.55919479e+02, -1.01184111e+04,
        -3.03154785e+02,  7.72204437e+01,  2.01886078e+02,  2.00063095e+01,
        -8.33727173e+02,  3.59986969e+02, -1.23200119e+02, -2.39919479e+02,
        -1.01024111e+04, -2.87154785e+02,  9.32204437e+01,  2.17886078e+02,
         3.60063095e+01, -8.17727173e+02,  3.75986969e+02, -1.07200119e+02,
        -2.23919479e+02, -1.00864111e+04, -2.71154785e+02,  1.09220436e+02,
         2.33886078e+02,  5.20063095e+01, -8.01727173e+02,  3.91986969e+02,
        -9.12001190e+01, -2.079

In [38]:
results_1 = tf.stack([pred_boxes0, pred_boxes1, pred_boxes2, pred_boxes3], axis=1)
results_1

<tf.Tensor: id=572, shape=(900, 4), dtype=float32, numpy=
array([[ -189.64981 ,    83.888954,  -100.17084 ,   102.60659 ],
       [ -391.71036 ,  -258.4771  ,   164.51456 ,   237.30634 ],
       [  652.4704  , -3587.796   ,   801.9206  ,  3828.9146  ],
       ...,
       [   17.035019,  -193.53137 ,   298.96185 ,  -137.4273  ],
       [  301.69275 ,   307.94244 ,   332.75525 ,   420.1222  ],
       [  -70.782684, -3233.0981  ,   536.1638  ,   -31.586304]],
      dtype=float32)>

In [39]:
b0 = tf.maximum(tf.minimum(boxes[:, 0], im_info[1] - 1), 0)
b1 = tf.maximum(tf.minimum(boxes[:, 1], im_info[0] - 1), 0)
b2 = tf.maximum(tf.minimum(boxes[:, 2], im_info[1] - 1), 0)
b3 = tf.maximum(tf.minimum(boxes[:, 3], im_info[0] - 1), 0)
b0, b1, b2, b3

(<tf.Tensor: id=580, shape=(900,), dtype=float32, numpy=
 array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         12.,   0.,   0.,   0.,   0.,   0.,   8.,   0.,   0.,  28.,   0.,
          0.,   0.,   0.,   0.,  24.,   0.,   0.,  44.,   0.,   0.,  12.,
          0.,   0.,  40.,   0.,   0.,  60.,  16.,   0.,  28.,   0.,   0.,
         56.,   0.,   0.,  76.,  32.,   0.,  44.,   0.,   0.,  72.,   8.,
          0.,  92.,  48.,   0.,  60.,   0.,   0.,  88.,  24.,   0., 108.,
         64.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,  12.,   0.,   0.,   0.,   0.,   0.,   8.,   0.,   0.,
         28.,   0.,   0.,   0.,   0.,   0.,  24.,   0.,

In [41]:
results_2 = tf.stack([b0, b1, b2, b3], axis=1)
results_2

<tf.Tensor: id=606, shape=(900, 4), dtype=float32, numpy=
array([[  0.,   0.,  99.,  55.],
       [  0.,   0., 159., 103.],
       [  0.,   0., 159., 159.],
       ...,
       [108.,  64., 159., 159.],
       [ 64.,   0., 159., 159.],
       [  0.,   0., 159., 159.]], dtype=float32)>

In [42]:
# Non-maximal suppression
indices = tf.image.non_max_suppression(results_2, scores, max_output_size=post_nms_topN, iou_threshold=nms_thresh)
indices

<tf.Tensor: id=610, shape=(54,), dtype=int32, numpy=
array([821, 246, 498, 480, 120, 435, 192, 399, 786, 759, 732, 138, 615,
         6, 807, 447, 177,  51,  42,  78, 885, 858, 840, 456, 726, 453,
        93, 510, 501, 492, 483, 195, 771, 762, 753, 813,  12,  57,  39,
        28, 888, 891, 534,   0, 441, 504, 405, 612, 567, 450, 864, 810,
        36,  81])>

In [43]:
tf.gather?

In [46]:
boxes = tf.gather(results_2, indices)
boxes = tf.cast(boxes, dtype=tf.float32)
scores_ = tf.gather(scores, indices)
scores_ = tf.reshape(scores_, shape=(-1, 1))
boxes, scores_

(<tf.Tensor: id=620, shape=(54, 4), dtype=float32, numpy=
 array([[  0.,   0., 159., 159.],
        [ 56.,   0., 159., 103.],
        [ 24.,  24., 151., 151.],
        [  0.,  24., 119., 151.],
        [  0.,   0., 119.,  87.],
        [ 72.,   8., 159., 135.],
        [  0.,   0.,  87., 103.],
        [  8.,   8., 135., 135.],
        [ 56.,  72., 159., 159.],
        [  8.,  72., 135., 159.],
        [  0.,  72.,  87., 159.],
        [ 24.,   0., 151.,  87.],
        [ 72.,  40., 159., 159.],
        [  0.,   0.,  51.,  95.],
        [108.,  48., 159., 159.],
        [108.,   0., 159., 159.],
        [108.,   0., 159., 111.],
        [ 44.,   0., 131.,  95.],
        [ 28.,   0., 115.,  95.],
        [ 92.,   0., 159.,  95.],
        [ 72.,  88., 159., 159.],
        [ 24.,  88., 151., 159.],
        [  0.,  88., 119., 159.],
        [  0.,   0.,  51., 159.],
        [  0.,  48.,  51., 159.],
        [  0.,  24.,  71., 151.],
        [  0.,   0.,  71.,  87.],
        [ 60.,   0., 147

In [47]:
# Only support single image as input
batch_inds = tf.zeros((tf.shape(indices)[0], 1), dtype=tf.float32)
blob = tf.concat([batch_inds, boxes], 1)
batch_inds, blob

(<tf.Tensor: id=634, shape=(54, 1), dtype=float32, numpy=
 array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], dtype=float32)>,
 <tf.Tensor: id=636, shape=(54, 5), dtype=float32, numpy=
 array([[  0.,   0.,   0., 159., 159.],
        [  0.,  56.,   0., 159., 103.],
        [  0.,  24.,  24., 151

In [1]:
import cython