In [1]:
import tensorflow as tf 

In [3]:
scale=32
ratios=(0.5, 1, 2)
scales, ratios = tf.meshgrid([float(scale)], ratios)
scales, ratios

(<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
 array([[32.],
        [32.],
        [32.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 1), dtype=float32, numpy=
 array([[0.5],
        [1. ],
        [2. ]], dtype=float32)>)

In [4]:
tf.meshgrid?

In [6]:
scales = tf.reshape(scales, [-1])
ratios = tf.reshape(ratios, [-1])
scales, ratios

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([32., 32., 32.], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.5, 1. , 2. ], dtype=float32)>)