In [2]:
import tensorflow as tf 

In [3]:
scale=32
ratios=(0.5, 1, 2)
scales, ratios = tf.meshgrid([float(scale)], ratios)
scales, ratios

(<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
 array([[32.],
        [32.],
        [32.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 1), dtype=float32, numpy=
 array([[0.5],
        [1. ],
        [2. ]], dtype=float32)>)

In [4]:
tf.meshgrid?

In [5]:
scales = tf.reshape(scales, [-1])
ratios = tf.reshape(ratios, [-1])
scales, ratios

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([32., 32., 32.], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.5, 1. , 2. ], dtype=float32)>)

In [6]:
heights = scales / tf.sqrt(ratios)
widths = scales * tf.sqrt(ratios) 
heights, widths

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([45.254833, 32.      , 22.627417], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([22.627417, 32.      , 45.254833], dtype=float32)>)

In [7]:
tf.multiply?

In [8]:
# Enumerate shifts in feature space
feature_shape = (10, 10)
feature_stride = 2
shifts_y = tf.multiply(tf.range(feature_shape[0]), feature_stride)
shifts_x = tf.multiply(tf.range(feature_shape[1]), feature_stride)
shifts_y, shifts_x

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])>,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])>)

In [9]:
shifts_x, shifts_y = tf.cast(shifts_x, tf.float32), tf.cast(shifts_y, tf.float32)
shifts_x, shifts_y = tf.meshgrid(shifts_x, shifts_y)
shifts_x, shifts_y

(<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
 array([[ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
        [ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
        [ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
        [ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
        [ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
        [ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
        [ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
        [ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
        [ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
        [ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.]], dtype=float32)>,
 <tf.Tensor: shape=(10, 10), dtype=float32, numpy=
 array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
        [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
        [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
        [ 8.,  8.,  8.,  8.,  8.,  8.,  

In [11]:
# Enumerate combinations of shifts, widths, and heights
box_widths, box_centers_x = tf.meshgrid(widths, shifts_x)
box_widths, box_centers_x

(<tf.Tensor: shape=(100, 3), dtype=float32, numpy=
 array([[22.627417, 32.      , 45.254833],
        [22.627417, 32.      , 45.254833],
        [22.627417, 32.      , 45.254833],
        [22.627417, 32.      , 45.254833],
        [22.627417, 32.      , 45.254833],
        [22.627417, 32.      , 45.254833],
        [22.627417, 32.      , 45.254833],
        [22.627417, 32.      , 45.254833],
        [22.627417, 32.      , 45.254833],
        [22.627417, 32.      , 45.254833],
        [22.627417, 32.      , 45.254833],
        [22.627417, 32.      , 45.254833],
        [22.627417, 32.      , 45.254833],
        [22.627417, 32.      , 45.254833],
        [22.627417, 32.      , 45.254833],
        [22.627417, 32.      , 45.254833],
        [22.627417, 32.      , 45.254833],
        [22.627417, 32.      , 45.254833],
        [22.627417, 32.      , 45.254833],
        [22.627417, 32.      , 45.254833],
        [22.627417, 32.      , 45.254833],
        [22.627417, 32.      , 45.254833],
   

In [12]:
box_heights, box_centers_y = tf.meshgrid(heights, shifts_y)
box_heights, box_centers_y

(<tf.Tensor: shape=(100, 3), dtype=float32, numpy=
 array([[45.254833, 32.      , 22.627417],
        [45.254833, 32.      , 22.627417],
        [45.254833, 32.      , 22.627417],
        [45.254833, 32.      , 22.627417],
        [45.254833, 32.      , 22.627417],
        [45.254833, 32.      , 22.627417],
        [45.254833, 32.      , 22.627417],
        [45.254833, 32.      , 22.627417],
        [45.254833, 32.      , 22.627417],
        [45.254833, 32.      , 22.627417],
        [45.254833, 32.      , 22.627417],
        [45.254833, 32.      , 22.627417],
        [45.254833, 32.      , 22.627417],
        [45.254833, 32.      , 22.627417],
        [45.254833, 32.      , 22.627417],
        [45.254833, 32.      , 22.627417],
        [45.254833, 32.      , 22.627417],
        [45.254833, 32.      , 22.627417],
        [45.254833, 32.      , 22.627417],
        [45.254833, 32.      , 22.627417],
        [45.254833, 32.      , 22.627417],
        [45.254833, 32.      , 22.627417],
   

In [26]:
arr = [box_centers_y, box_centers_x]
arr_ = tf.stack([box_centers_y, box_centers_x], axis=2)
arr, arr_

([<tf.Tensor: shape=(100, 3), dtype=float32, numpy=
  array([[ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 0.,  0.,  0.],
         [ 2.,  2.,  2.],
         [ 2.,  2.,  2.],
         [ 2.,  2.,  2.],
         [ 2.,  2.,  2.],
         [ 2.,  2.,  2.],
         [ 2.,  2.,  2.],
         [ 2.,  2.,  2.],
         [ 2.,  2.,  2.],
         [ 2.,  2.,  2.],
         [ 2.,  2.,  2.],
         [ 4.,  4.,  4.],
         [ 4.,  4.,  4.],
         [ 4.,  4.,  4.],
         [ 4.,  4.,  4.],
         [ 4.,  4.,  4.],
         [ 4.,  4.,  4.],
         [ 4.,  4.,  4.],
         [ 4.,  4.,  4.],
         [ 4.,  4.,  4.],
         [ 4.,  4.,  4.],
         [ 6.,  6.,  6.],
         [ 6.,  6.,  6.],
         [ 6.,  6.,  6.],
         [ 6.,  6.,  6.],
         [ 6.,  6.,  6.],
         [ 6.,  6.,  6.],
         [ 6

In [13]:
# Reshape to get a list of (y, x) and a list of (h, w)
box_centers = tf.reshape(tf.stack([box_centers_y, box_centers_x], axis=2), (-1, 2))
box_sizes = tf.reshape(tf.stack([box_heights, box_widths], axis=2), (-1, 2))
box_centers, box_sizes

(<tf.Tensor: shape=(300, 2), dtype=float32, numpy=
 array([[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  2.],
        [ 0.,  2.],
        [ 0.,  2.],
        [ 0.,  4.],
        [ 0.,  4.],
        [ 0.,  4.],
        [ 0.,  6.],
        [ 0.,  6.],
        [ 0.,  6.],
        [ 0.,  8.],
        [ 0.,  8.],
        [ 0.,  8.],
        [ 0., 10.],
        [ 0., 10.],
        [ 0., 10.],
        [ 0., 12.],
        [ 0., 12.],
        [ 0., 12.],
        [ 0., 14.],
        [ 0., 14.],
        [ 0., 14.],
        [ 0., 16.],
        [ 0., 16.],
        [ 0., 16.],
        [ 0., 18.],
        [ 0., 18.],
        [ 0., 18.],
        [ 2.,  0.],
        [ 2.,  0.],
        [ 2.,  0.],
        [ 2.,  2.],
        [ 2.,  2.],
        [ 2.,  2.],
        [ 2.,  4.],
        [ 2.,  4.],
        [ 2.,  4.],
        [ 2.,  6.],
        [ 2.,  6.],
        [ 2.,  6.],
        [ 2.,  8.],
        [ 2.,  8.],
        [ 2.,  8.],
        [ 2., 10.],
        [ 2., 10.],
        [

In [16]:
anchors_left = box_centers - 0.5 * box_sizes
anchors_right = box_centers + 0.5 * box_sizes
anchors_left, anchors_right

(<tf.Tensor: shape=(300, 2), dtype=float32, numpy=
 array([[-22.627417 , -11.313708 ],
        [-16.       , -16.       ],
        [-11.313708 , -22.627417 ],
        [-22.627417 ,  -9.313708 ],
        [-16.       , -14.       ],
        [-11.313708 , -20.627417 ],
        [-22.627417 ,  -7.3137083],
        [-16.       , -12.       ],
        [-11.313708 , -18.627417 ],
        [-22.627417 ,  -5.3137083],
        [-16.       , -10.       ],
        [-11.313708 , -16.627417 ],
        [-22.627417 ,  -3.3137083],
        [-16.       ,  -8.       ],
        [-11.313708 , -14.627417 ],
        [-22.627417 ,  -1.3137083],
        [-16.       ,  -6.       ],
        [-11.313708 , -12.627417 ],
        [-22.627417 ,   0.6862917],
        [-16.       ,  -4.       ],
        [-11.313708 , -10.627417 ],
        [-22.627417 ,   2.6862917],
        [-16.       ,  -2.       ],
        [-11.313708 ,  -8.627417 ],
        [-22.627417 ,   4.6862917],
        [-16.       ,   0.       ],
        [-11.

In [17]:
anchors = [box_centers - 0.5 * box_sizes, box_centers + 0.5 * box_sizes]
anchors 

[<tf.Tensor: shape=(300, 2), dtype=float32, numpy=
 array([[-22.627417 , -11.313708 ],
        [-16.       , -16.       ],
        [-11.313708 , -22.627417 ],
        [-22.627417 ,  -9.313708 ],
        [-16.       , -14.       ],
        [-11.313708 , -20.627417 ],
        [-22.627417 ,  -7.3137083],
        [-16.       , -12.       ],
        [-11.313708 , -18.627417 ],
        [-22.627417 ,  -5.3137083],
        [-16.       , -10.       ],
        [-11.313708 , -16.627417 ],
        [-22.627417 ,  -3.3137083],
        [-16.       ,  -8.       ],
        [-11.313708 , -14.627417 ],
        [-22.627417 ,  -1.3137083],
        [-16.       ,  -6.       ],
        [-11.313708 , -12.627417 ],
        [-22.627417 ,   0.6862917],
        [-16.       ,  -4.       ],
        [-11.313708 , -10.627417 ],
        [-22.627417 ,   2.6862917],
        [-16.       ,  -2.       ],
        [-11.313708 ,  -8.627417 ],
        [-22.627417 ,   4.6862917],
        [-16.       ,   0.       ],
        [-11.

In [20]:
tf.concat?

In [18]:
boxes = tf.concat([box_centers - 0.5 * box_sizes,
                    box_centers + 0.5 * box_sizes], axis=1)
boxes 

<tf.Tensor: shape=(300, 4), dtype=float32, numpy=
array([[-22.627417 , -11.313708 ,  22.627417 ,  11.313708 ],
       [-16.       , -16.       ,  16.       ,  16.       ],
       [-11.313708 , -22.627417 ,  11.313708 ,  22.627417 ],
       ...,
       [ -4.6274166,   6.6862917,  40.62742  ,  29.31371  ],
       [  2.       ,   2.       ,  34.       ,  34.       ],
       [  6.6862917,  -4.6274166,  29.31371  ,  40.62742  ]],
      dtype=float32)>

In [27]:
tf.stack?